sonar.java.jdkHome=C:\Program Files\Java\jdk-17
# Unique project key
sonar.projectKey=Request_handler_server

# Project name in SonarQube
sonar.projectName=Request_handler_server

# Project version
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8

# SonarQube server URL
sonar.host.url=http://192.168.3.42:9000

# Login token (generate in SonarQube -> My Account -> Security -> Tokens)
sonar.token=sqa_f7f3903d50bd572446d8dee7fd4adc20be538deb
